@basicUrl=http://localhost:3000/api

POST {{basicUrl}}/cars
Content-Type: application/json

{
 "make":"suzuki 123",
 "model ":"suzuki",
 "image":"https://muaxegiatot.vn/wp-content/uploads/2022/04/suzuki-xl7-sport-limited-2022-xl7-dac-biet-bo-sung-goi-trang-bi-2-640x427.jpg",
 "description":"sieu ben"
}

###
GET {{basicUrl}}/car/01GC737JC0K65M95F7SNFPXDHG
Content-Type: application/json

###
GET {{basicUrl}}/search?civic
Content-Type: application/json